### ISSUE TITLE
Getting Failed opening 'Mage/Googleshoppingapi/Helper/Data.php' on production site

### ISSUE THREAD

**Issue by AshleshaGawade** [bluevisiontec/GoogleShoppingApi#10]
I had installed this extension on development which worked successfully.
Later when i pulled it to production instance it gives me the follwing error on refreshing caches:

2015-02-26T23:46:19+00:00 ERR (3): Warning: include(Mage/Googleshoppingapi/Helper/Data.php): failed to open stream: No such file or directory  in /var/www/nykmage/lib/Varien/Autoload.php on line 93

and admin panel becomes blank.
I have 3 instances on production of that i have installed it in only one instance which is used for admin panel.
Can you please provide some help to this, if you have any idea?

**Comment by jonatanaxe** [comment]
I am also with this error :(

**Comment by schnere** [comment]
The error occurs when the origininal Magento GoogleShopping Api module is not installed.
But with the next commit I will remove the last depencies on the original module, so that this should be fixed.

**Comment by pavelnovitsky** [comment]
Hi, @schnere!
You removed all references to googleshopping in data install file. Actually, `$installer->getTable('googleshopping/…')` should stay, because now you select data from `googleshoppingapi/types` and insert into the same table. Same with attributes and items.

Using `Mage::helper('googleshoppingapi')->isModuleEnabled('Mage_GoogleShopping')` is enough for compatibilty.

**Comment by schnere** [comment]
@pavelnovitsky Thanks for the notice. Of course, you are right. I will fix this again in the next commit..
