### ISSUE TITLE
how to get rid of _store

### ISSUE THREAD

**Issue by chingulito** [bluevisiontec/GoogleShoppingApi#53]
The module is working perfect. That fast that my 1700 items any you touch is updated instantly on google

However O notice after migrating from data file feed to API start to update the landing URK to the following format

http://mysite.com/m-product.html?___store=mystore

on Magento admin
system---> configuration-->Web--(Default conf.) ---Add Store Code to Urls -- set to NO

Ps: This was a multiple store, however all were deleted and keeping only one

I do not know if that is the reason, dont know how to fix if that is the problem

Thanks
Marcelo

**Comment by schnere** [comment]
Actually, this might be a little confusing. But the store code gets added if you set this option to "NO".
Otherwise Magento would add the store code as URL path so the module does not need to append it...

But I'll add an option to disable the addition of the store code within the module configuration (System -> Configuration -> GoogleShoppingAPI -> URL parameters -> Add store code to url)

**Comment by chingulito** [comment]
Hello thank you for your responseI have done that first thing I did, did not work still was sending the ID_StoreNumber
I modified your scriptIf you like i can copy what i did
Thanks again marcelo
