### ISSUE TITLE
update / synchronize products in bulk not working

### ISSUE THREAD

**Issue by punitgadhiya** [bluevisiontec/GoogleShoppingApi#59]
Hi, I have noticed that after uploading ±500 products the feed kills itself. 
Perhaps because the process has been running to long? there is 10,000+ products and i am trying to synchronize all product it will kills feed after approx uploading 500 products. is there any way so, that i can upload bulk product? Why it stops after 500 products?
Thank you.

**Comment by behunin** [comment]
I have had the same problem and I believe that when google-api-php-client merges pull request #654:  https://github.com/google/google-api-php-client/pull/654 we should implement into GoogleShoppingApi.
This new pull uses the GuzzleHttp Library: http://guzzle.readthedocs.org/en/latest/index.html which is very good at sending large requests.

**Comment by punitgadhiya** [comment]
@Behunin cant get it :( how to do?

**Comment by behunin** [comment]
Which branch of google-api-php-client are you on?

**Comment by jay-saint** [comment]
I have similar problem, I freequently get time outs trying to synchronize products.  It used to work for me, by more and more I find that my PLA campaigns are stopping because GoogleShopping API has failed to sync and google merchant has dropped my products because they expire after 30 days.
I am currently using the Google API php 1.4 because previous issues recommended it as a solution to the White screen problem.
I am looking at commercial alternatives if anyone has recommendations.

**Comment by behunin** [comment]
The main problem here is that the code in this project does not utilize batch requests. When you are adding multiple products they are all sent in serial, which as you can imagine takes a long time for 500+ requests and the resulting responses to be completed. When I looked into how to implement batching I noticed that google-api-php-client has batching but they are working on a much better solution right now that uses GuzzleHttp, so I stopped my development and will continue after they have finished refactoring. 
I have used the google shopping feed from rocket web and other feed generators with success but grew tired of the problems that come with google feeds. Mainly the fact that when you make any changes to your catalog a whole new feed has to be generated, sent, and parsed. Then I started to have this nagging problem where products would show up in google as another item in our catalog, which was usually disabled on our site. This caused customers to call in asking why an item that is in google shopping for dirt cheap is not available on our site. :(
From what I can tell google will be done refactoring in November and when they are done I will work with @bluevisiontec on implementing batching. I need this module to work right for 1000+ products and I am not going back to feed generators.

**Comment by schnere** [comment]
I know about the problems with a big catalog. For this reason batch processing was always an important TODO on my list. 
As you can see in the latest commits I have started to implement batch processing. For the moment at least for manual synchronization (Through the backend). 
Please help me to get this ready by testing and tell me if improves the synchronization speed for your catalog. 

Furthermore I will introduce a shell script which gives you the ability to create a separate cronjob.

**Comment by behunin** [comment]
Which branch of the google-api-php-client do you test against?

**Comment by schnere** [comment]
Master branch - release 1.1.4 with autoloader fix. Check for 1.1.5 is also on the TODO-list...

**Comment by behunin** [comment]
OK I will switch over to 1.1.4 for testing but I have been working with the v2-dev branch and will test with that as well.

**Comment by schnere** [comment]
@Behunin I've uploaded a really early version of the shell script in the last commit.
You might find it helpful for testing:

```
php -f shell/googleshopping.php -- --action syncitems --storeid 1
```

Please make sure that the same php.ini is used as your webserver uses:

```
PHPRC="/path/to/php/conf/" php -f shell/googleshopping.php -- --action syncitems --storeid 1
```

**Comment by JustinElst** [comment]
I have made some improvements in https://github.com/bluevisiontec/GoogleShoppingApi/pull/70 But I suspect that you will need to add https://github.com/bluevisiontec/GoogleShoppingApi/pull/67 too which needs some reconfiguration in magento/google console.

**Comment by Sebastian700** [comment]
I have two issues:
1. When the price change on my website, the module retains the old values for about a week on different products and google merchant center disproved 150 of my top seller products for a week, due to price difference. (I repriced the whole site and I did a bulk re-submission, after that I also did one at a time re-submission, than I deleted the products and resubmitted them to google. all over, at that point it started to use the correct price.)

I'm trying to use an automatic reprice if the API work like that I wont have any inventory on Google Shopping.
1. When the product is out of stock, it still stay in stock in google shopping and it continues to hit me with charges for products out of stock. 

Any Ideas how to fix this?
